# Generated by Django 4.0.1 on 2022-02-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_issue_user_project_issue_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Overdue', 'Overdue'), ('Due Now', 'Due Now'), ('Due Later', 'Due Later')], default='Due Later', max_length=20),
        ),
    ]
