# Generated by Django 4.0.1 on 2022-02-05 02:03

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_issue_priority_issue_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='return_date',
            field=models.DateField(default=base.models.due_date),
        ),
    ]
